application: file-compression-service
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: .*
  script: main.app
  secure: always

libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"
- name: ssl
  version: latest

env_variables:
    BOTO_CONFIG: ./boto
