python post.py "hello" "hi #freedom"
echo "Done 1"
python post.py "hello" "hi #freedom"
echo "Done 2"
python post.py "dj" "hi #freedom2"
echo "Done 3"
python post.py "djk" "hi #freedom2"
echo "Done 4"
python post.py "dkothari" "hi #freedom #free"
echo "Done 5"
python post.py "h" "hi #freedom"
echo "Done 6"
python post.py "h" "hi #freedom2"
echo "Done 7"
python post.py "hey" "hi #freedom1 #free"
echo "Done 8"
python post.py "hey" "hi #freedom1 #free"
echo "Done 9"
